name = "markets-feeds"
main = "frontend/dist/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && npm install && npm run build"

[env.production]
name = "markets-feeds"

[env.staging]
name = "markets-feeds-staging"