# PagesCMS Configuration for Markets Feeds v2
# https://pagescms.org/docs/configuration/

# Media Configuration
media:
  input: public/media
  output: /media

# Content Collections
content:
  # Ideas/Discovery Posts
  - name: ideas
    label: Ideas & Insights
    path: content/ideas
    type: collection
    view:
      fields: [title, author, publishedAt, type]
      primaryField: title
      dateField: publishedAt
    fields:
      - name: title
        label: Title
        type: string
        required: true
        help: Brief, descriptive title for the insight

      - name: slug
        label: URL Slug
        type: string
        required: true
        help: URL-friendly version of the title

      - name: author
        label: Author
        type: select
        required: true
        default: research-team
        options:
          - { label: "Research Team", value: "research-team" }
          - { label: "Market Analysis", value: "market-analysis" }
          - { label: "Economic Research", value: "economic-research" }
          - { label: "Tech Insights", value: "tech-insights" }
          - { label: "Policy Analysis", value: "policy-analysis" }

      - name: authorName
        label: Author Display Name
        type: string
        required: true
        default: Research Team

      - name: authorAvatar
        label: Author Avatar
        type: string
        help: Two-letter initials or emoji

      - name: publishedAt
        label: Publication Date
        type: date
        required: true
        default: now

      - name: type
        label: Post Type
        type: select
        required: true
        default: text
        options:
          - { label: "Text Post", value: "text" }
          - { label: "Link with Preview", value: "link" }
          - { label: "Video Embed", value: "video" }
          - { label: "Tweet Embed", value: "tweet" }
          - { label: "Image Post", value: "image" }

      - name: content
        label: Content
        type: text
        required: true
        help: Main content of the post (supports markdown)

      - name: tags
        label: Tags
        type: string
        multiple: true
        help: Comma-separated tags for categorization

      - name: priority
        label: Priority
        type: select
        default: normal
        options:
          - { label: "Normal", value: "normal" }
          - { label: "High", value: "high" }
          - { label: "Breaking", value: "breaking" }

      - name: isPrivate
        label: Private Post
        type: boolean
        default: false
        help: Only visible to team members

      - name: team
        label: Team Scope
        type: select
        required: false
        options:
          - { label: "All Teams", value: "all" }
          - { label: "Research", value: "research" }
          - { label: "Analysis", value: "analysis" }
          - { label: "Editorial", value: "editorial" }

      # Link-specific fields
      - name: linkUrl
        label: Link URL
        type: string
        condition: { field: type, equals: "link" }
        help: URL for link preview generation

      - name: linkTitle
        label: Link Title
        type: string
        condition: { field: type, equals: "link" }
        help: Override title from automatic extraction

      - name: linkDescription
        label: Link Description
        type: text
        condition: { field: type, equals: "link" }
        help: Override description from automatic extraction

      - name: linkImage
        label: Link Image
        type: image
        condition: { field: type, equals: "link" }
        help: Override image from automatic extraction

      - name: linkDomain
        label: Link Domain
        type: string
        condition: { field: type, equals: "link" }
        help: Display domain (auto-extracted if not provided)

      # Video-specific fields
      - name: videoTitle
        label: Video Title
        type: string
        condition: { field: type, equals: "video" }

      - name: videoThumbnail
        label: Video Thumbnail
        type: image
        condition: { field: type, equals: "video" }

      - name: videoUrl
        label: Video URL
        type: string
        condition: { field: type, equals: "video" }
        help: YouTube, Vimeo, or direct video URL

      - name: videoDuration
        label: Video Duration
        type: string
        condition: { field: type, equals: "video" }
        help: Format like "12:34"

      - name: videoPlatform
        label: Video Platform
        type: select
        condition: { field: type, equals: "video" }
        options:
          - { label: "YouTube", value: "youtube" }
          - { label: "Vimeo", value: "vimeo" }
          - { label: "Twitter", value: "twitter" }
          - { label: "Direct Link", value: "direct" }

      # Tweet-specific fields
      - name: tweetAuthor
        label: Tweet Author
        type: string
        condition: { field: type, equals: "tweet" }

      - name: tweetHandle
        label: Tweet Handle
        type: string
        condition: { field: type, equals: "tweet" }
        help: Include @ symbol

      - name: tweetContent
        label: Tweet Content
        type: text
        condition: { field: type, equals: "tweet" }

      - name: tweetId
        label: Tweet ID
        type: string
        condition: { field: type, equals: "tweet" }
        help: For embedding original tweet

      - name: tweetAvatar
        label: Tweet Avatar URL
        type: string
        condition: { field: type, equals: "tweet" }

      # Image-specific fields
      - name: imageUrl
        label: Image
        type: image
        condition: { field: type, equals: "image" }
        required: true

      - name: imageAlt
        label: Image Alt Text
        type: string
        condition: { field: type, equals: "image" }
        required: true

      - name: imageCaption
        label: Image Caption
        type: string
        condition: { field: type, equals: "image" }

      # Engagement metrics (read-only, populated by system)
      - name: reactions
        label: Reactions
        type: object
        fields:
          - name: insights
            label: Insights Count
            type: number
            default: 0

          - name: comments
            label: Comments Count
            type: number
            default: 0

          - name: shares
            label: Shares Count
            type: number
            default: 0

      # Metadata
      - name: isEdited
        label: Edited
        type: boolean
        default: false
        help: Automatically set when post is modified

      - name: editedAt
        label: Last Edited
        type: date
        help: Automatically updated on edit

      - name: moderationStatus
        label: Moderation Status
        type: select
        default: approved
        options:
          - { label: "Approved", value: "approved" }
          - { label: "Pending Review", value: "pending" }
          - { label: "Rejected", value: "rejected" }
          - { label: "Flagged", value: "flagged" }

      - name: featured
        label: Featured Post
        type: boolean
        default: false
        help: Highlight this post in feeds

  # RSS Feed Sources (for reference and management)
  - name: sources
    label: RSS Sources
    path: content/sources
    type: collection
    view:
      fields: [name, url, category, active]
      primaryField: name
    fields:
      - name: name
        label: Source Name
        type: string
        required: true

      - name: slug
        label: URL Slug
        type: string
        required: true

      - name: url
        label: RSS URL
        type: string
        required: true

      - name: category
        label: Primary Category
        type: select
        required: true
        options:
          - { label: "Markets", value: "markets" }
          - { label: "Macro Economics", value: "macro" }
          - { label: "Policy", value: "policy" }
          - { label: "Research", value: "research" }
          - { label: "Technology", value: "technology" }
          - { label: "News", value: "news" }
          - { label: "Analysis", value: "analysis" }

      - name: description
        label: Description
        type: text

      - name: active
        label: Active
        type: boolean
        default: true

      - name: fetchFrequency
        label: Fetch Frequency (hours)
        type: number
        default: 4
        help: How often to check for new content

      - name: priority
        label: Source Priority
        type: select
        default: normal
        options:
          - { label: "High", value: "high" }
          - { label: "Normal", value: "normal" }
          - { label: "Low", value: "low" }

      - name: tags
        label: Default Tags
        type: string
        multiple: true
        help: Tags automatically applied to articles from this source

      - name: website
        label: Website URL
        type: string

      - name: favicon
        label: Favicon URL
        type: string

      - name: lastFetched
        label: Last Fetched
        type: date

      - name: articleCount
        label: Total Articles
        type: number
        default: 0

  # Team Configuration
  - name: team
    label: Team Settings
    path: content/config
    type: collection
    fields:
      - name: name
        label: Team Member Name
        type: string
        required: true

      - name: slug
        label: URL Slug
        type: string
        required: true

      - name: email
        label: Email
        type: string
        required: true

      - name: role
        label: Role
        type: select
        required: true
        options:
          - { label: "Admin", value: "admin" }
          - { label: "Editor", value: "editor" }
          - { label: "Contributor", value: "contributor" }
          - { label: "Viewer", value: "viewer" }

      - name: avatar
        label: Avatar
        type: image

      - name: bio
        label: Bio
        type: text

      - name: specialties
        label: Specialties
        type: string
        multiple: true
        help: Areas of expertise

      - name: active
        label: Active
        type: boolean
        default: true

      - name: notifications
        label: Email Notifications
        type: boolean
        default: true

# Site Configuration
site:
  name: Markets Feeds v2
  description: Financial intelligence hub with team insights
  url: https://your-domain.com
  logo: /media/logo.png

# Dashboard Configuration
dashboard:
  # Collections to show on dashboard
  collections:
    - ideas
    - sources
    - team

  # Quick actions
  actions:
    - name: New Insight
      collection: ideas
      icon: lightbulb

    - name: Add Source
      collection: sources
      icon: rss

    - name: Team Member
      collection: team
      icon: user

# Advanced Features
features:
  # Rich text editor
  richText:
    enabled: true
    toolbar: [bold, italic, link, heading, list, quote, code]

  # Media management
  media:
    enabled: true
    formats: [jpg, jpeg, png, gif, webp, svg, mp4, webm]
    maxSize: 10MB
    generateThumbnails: true

  # Search and filtering
  search:
    enabled: true
    fields: [title, content, tags, author]

  # Draft management
  drafts:
    enabled: true
    autosave: true
    autosaveInterval: 30s

  # Version control
  versioning:
    enabled: true
    maxVersions: 10

  # Collaboration
  collaboration:
    comments: true
    suggestions: true
    assignReviews: true

  # Scheduling
  scheduling:
    enabled: true
    timezone: UTC

  # Webhooks
  webhooks:
    enabled: true
    events: [create, update, delete, publish]

  # API access
  api:
    enabled: true
    authentication: bearer

  # Backup
  backup:
    enabled: true
    frequency: daily
    retention: 30d

# UI Customization
ui:
  theme: light
  primaryColor: "#1e40af"
  sidebarCollapsed: false
  
  # Custom branding
  branding:
    logo: /media/logo.png
    favicon: /media/favicon.ico
    title: Markets Feeds CMS

  # Layout preferences
  layout:
    showPreview: true
    previewMode: desktop
    showLineNumbers: true

# Security Settings
security:
  # Content validation
  validation:
    enabled: true
    sanitizeHtml: true
    validateUrls: true

  # Rate limiting
  rateLimit:
    enabled: true
    requests: 100
    window: 15m

  # CORS settings
  cors:
    enabled: true
    origins: ["https://your-domain.com"]

# Integration Settings
integrations:
  # Analytics
  analytics:
    enabled: false
    # provider: google
    # trackingId: GA_TRACKING_ID

  # Social media
  social:
    enabled: true
    platforms: [twitter, linkedin]

  # Email notifications
  email:
    enabled: true
    # provider: sendgrid
    # apiKey: SENDGRID_API_KEY

# Workflow Configuration
workflows:
  # Content approval
  approval:
    enabled: true
    required: false
    stages: [draft, review, approved, published]

  # Auto-publishing
  autoPublish:
    enabled: false
    schedule: "0 9 * * 1-5"  # 9 AM weekdays

# Performance Settings
performance:
  # Caching
  cache:
    enabled: true
    ttl: 3600

  # Compression
  compression:
    enabled: true
    level: 6

  # CDN
  cdn:
    enabled: false
    # provider: cloudflare
    # zone: your-zone-id