name = "markets-feeds-v2"
compatibility_date = "2024-01-01"

# Cron trigger for automated feed fetching
# Runs every 30 minutes
[[triggers]]
crons = ["*/30 * * * *"]

# Environment variables (add your own)
[vars]
ENVIRONMENT = "production"

# KV Namespaces for data storage
# [[kv_namespaces]]
# binding = "FEEDS_KV"
# id = "your-kv-namespace-id"

# D1 Database bindings
# [[d1_databases]]
# binding = "DB"
# database_name = "markets-feeds"
# database_id = "your-database-id"

# Durable Objects (for distributed cron)
# [[durable_objects.bindings]]
# name = "FEED_SCHEDULER"
# class_name = "FeedScheduler"

# Routes
[route]
pattern = "/*"
zone_id = ""