name: Aggregate RSS Feeds

on:
  schedule:
    # Run at 6:00 AM IST (00:30 UTC) - Pre-market
    - cron: '30 0 * * 1-5'
    # Run at 8:00 AM IST (02:30 UTC) - Morning update
    - cron: '30 2 * * 1-5'
    # Run at 9:45 AM IST (04:15 UTC) - Market open
    - cron: '15 4 * * 1-5'
    # Run at 12:00 PM IST (06:30 UTC) - Midday update
    - cron: '30 6 * * 1-5'
    # Run at 3:00 PM IST (09:30 UTC) - Market close
    - cron: '30 9 * * 1-5'
    # Run at 6:00 PM IST (12:30 UTC) - Post-market
    - cron: '30 12 * * 1-5'
    # Run at 9:00 PM IST (15:30 UTC) - Evening news
    - cron: '30 15 * * 1-5'
    # Weekend run at 9:00 AM IST (03:30 UTC)
    - cron: '30 3 * * 0,6'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [main]
    paths:
      - 'scripts/**'
      - '.github/workflows/aggregate-feeds.yml'

jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements.txt'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      - name: Run RSS aggregation
        run: |
          python scripts/aggregate_feeds_improved.py
        env:
          PYTHONUNBUFFERED: 1
          
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet src/content/links || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/content/links/*.json scripts/aggregator_state.json
          git diff --cached --quiet || git commit -m "Update RSS feeds [skip ci]"
          git push
          
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aggregation-logs
          path: aggregation.log
          retention-days: 7