name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Aggregate RSS Feeds"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'v2/package-lock.json'
          
      - name: Install dependencies
        working-directory: v2
        run: npm ci
        
      - name: Inject build timestamp into service worker
        working-directory: v2
        run: |
          BUILD_TIME=$(date +%s)
          if [ -f "public/sw.js" ]; then
            sed -i "s/const CACHE_VERSION = '2.1';/const CACHE_VERSION = '2.1-$BUILD_TIME';/" public/sw.js
            echo "Build timestamp: $BUILD_TIME"
          else
            echo "Service worker not found, skipping timestamp injection"
          fi
          
      - name: Build Astro site
        working-directory: v2
        run: npm run build-only
        env:
          NODE_ENV: production
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: markets-feeds
          directory: v2/dist
          wranglerVersion: '3'
          
      - name: Create deployment status
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: []
            });
            
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: 'https://markets-feeds.pages.dev'
            });