name: Fetch RSS Feeds

on:
  schedule:
    # Run at specific IST times (IST = UTC + 5:30)
    # 4:00 AM IST = 10:30 PM UTC (previous day)
    - cron: '30 22 * * *'
    # 6:00 AM IST = 12:30 AM UTC
    - cron: '30 0 * * *'
    # 8:00 AM IST = 2:30 AM UTC
    - cron: '30 2 * * *'
    # 10:00 AM IST = 4:30 AM UTC
    - cron: '30 4 * * *'
    # 3:00 PM IST = 9:30 AM UTC
    - cron: '30 9 * * *'
    # 6:00 PM IST = 12:30 PM UTC
    - cron: '30 12 * * *'
    # 9:00 PM IST = 3:30 PM UTC
    - cron: '30 15 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: cd v2 && npm install
    
    - name: Fetch RSS feeds
      run: cd v2 && npm run fetch-feeds
      env:
        NODE_ENV: production
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'Feed Bot'
        git config --global user.email 'bot@markets-feeds.com'
        
        # Check if there are changes
        if [ -n "$(git status --porcelain v2/content/links/)" ]; then
          git add v2/content/links/*.json
          git add v2/fetch-report.json
          git commit -m "🤖 Update feeds - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
          echo "✅ Changes pushed to repository"
        else
          echo "ℹ️ No new articles to commit"
        fi
    
    - name: Upload fetch report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: fetch-report
        path: v2/fetch-report.json
        retention-days: 7
    
    - name: Check for errors and notify
      if: failure()
      run: |
        echo "❌ Feed fetch failed! Check the logs for details."
        # Optional: Add Slack/Discord webhook notification here
        # curl -X POST ${{ secrets.SLACK_WEBHOOK }} -d '{"text":"Feed fetch failed!"}'