name: Fetch RSS Feeds

on:
  schedule:
    # Run at 5 AM, 10 AM, 6 PM IST (11:30 PM, 4:30 AM, 12:30 PM UTC)
    - cron: '30 23 * * *'  # 5:00 AM IST (11:30 PM UTC previous day)
    - cron: '30 4 * * *'   # 10:00 AM IST (4:30 AM UTC)  
    - cron: '30 12 * * *'  # 6:00 PM IST (12:30 PM UTC)
  workflow_dispatch:  # Allow manual triggering
    inputs:
      limit_feeds:
        description: 'Limit number of feeds to process (for testing)'
        required: false
        default: ''
        type: string

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Give plenty of time for all feeds
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'worker/package-lock.json'
        
    - name: Install dependencies
      run: npm install node-fetch
        
    - name: Run RSS Feed Fetcher
      run: node scripts/fetch-feeds.js